# Generated by Django 3.0 on 2019-12-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouhassan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neibourhood', models.CharField(choices=[('البحوري', 'albohourey'), ('البسويد', 'albousayed'), ('الصبخة', ' alsabakha'), ('الابد', 'allabed'), ('الكازية', 'alkazea القديمة'), ('البسويد', 'albousoued')], default='البحوري', max_length=20)),
            ],
        ),
    ]
